### ISSUE TITLE
After first launch the app should present the balance page - no account setup 

### ISSUE THREAD

**Issue by n074v41l4bl34u** [HODLERTECH/HODLER-Android-App#18]
The free apps are for casual users, so it should be usable from the first screen.

Right now the user is forced to setup the account with passwords and write down the seed - this is great for the uber-secure HODLER hardware wallet but scares away the casual users. My mom or GF will never want to look at it, let alone use it if I force this setup screen down her throat. Just ain't gonna happen - we all know that.

The setup should be done automatically, with some default generic algorithm for generating seed/password. All successful secure communicators do it that way - the user is secure by default and can see the encryption keys if needed but does not have to set them up him/herself.

All in all, the wallet's main screen with pre-setup accounts should be available to the user at first launch.

**Comment by HODLERTECH** [comment]
1. User should set up password
2. Seed is created in background
3. User have access to his wallet but there are some reminders to save the seed on paper
4. Password is required to show the seed

**Comment by HODLERTECH** [comment]
Done
