### ISSUE TITLE
The whole seed should be selectable and copyable - not just single words

### ISSUE THREAD

**Issue by n074v41l4bl34u** [HODLERTECH/HODLER-Android-App#20]
Right now only single words can be selected and copied. I know the seed should not be stored digitally for security reasons but it is really up to the user how he/she decides to store their seed.

The app should help with getting the information about seed, so it should be selectable/copyable as a whole text, not just single words.

**Comment by HODLERTECH** [comment]
Hello.

You suggested: In the installation process, would be good the option
to copy the seed text.

Unfortunately seed shouldn't be copied for security reasons, there is
a lot of malware which can capture clipboard and send the seed to
attacker. Backup seed should be saved on paper or transcribed to a
password management program.

**Comment by n074v41l4bl34u** [comment]
OK, if there's no possibility to isolate clipboard management from malware then I understand - better safe than sorry.
