### ISSUE TITLE
HODLER app requires non-obvious permissions

### ISSUE THREAD

**Issue by n074v41l4bl34u** [HODLERTECH/HODLER-Android-App#26]
![screenshot_2018-07-02-18-25-47-758_com google android packageinstaller](https://user-images.githubusercontent.com/657784/42292814-8bd61616-7fd5-11e8-942f-271aac2dc7a6.png)

It is not at all obvious to me why does the app require location settings or access to the phone status/identity.

The app should require the least permissions it can work with and if possible ask for user permission when those permissions are actually needed. When I see an app that during installation asks to get all the weird permissions all in one go, I get very cautious and think twice if I want it on my phone.

For example: it would be more user-friendly if the app asked for the permission to take pictures/video only if the user decides to use the QR code scanner - otherwise the permission is not needed and the user should not be bothered.

**Comment by HODLERTECH** [comment]
Good suggestion, thank you
