### ISSUE TITLE
Sent, unconfirmed transactions should be immediately deducted from the balance of available balance

### ISSUE THREAD

**Issue by HODLERTECH** [HODLERTECH/HODLER-Android-App#37]
When I send eg ETH, funds are still in the wallet. I have to wait for confirmation of the sent transaction to know how much money I have and how much extra I can send.

**Comment by DanielMazurFL4RE** [comment]
This is a drawback of Ethereum deamon, but maybe useful when transaction stuck due to small gas price. User can "push" transaction by sending the transaction with same nonce but with higher gas price until the transaction goes confirmed.
