### ISSUE TITLE
The location of the "Synchronize" button should be the same in all program windows

### ISSUE THREAD

**Issue by HODLERTECH** [HODLERTECH/HODLER-Android-App#47]
Need help in determining the position of the button

**Comment by raven6679** [comment]
Sync is almost always placed on top menubar, as second or third icon from right.

**Comment by raven6679** [comment]
Also, "pulling down" gesture should work.

**Comment by raven6679** [comment]
https://www.pinterest.co.uk/pin/279715826833109816/
