### ISSUE TITLE
Version 0.5.5 will not install while 0.5.3 is installed - no update, no error message

### ISSUE THREAD

**Issue by n074v41l4bl34u** [HODLERTECH/HODLER-Android-App#49]
While version 0.5.3 is installed the system on Xiaomi 5 will not let me install 0.5.5 - it does not update the app nor does it present any error. It tries to install the app and then just shows a message that the app was not installed.

Might not be a bug, I do not know how installation/update scenario works on Android. However, as a vanilla user I would expect the final version of the wallet to seamlessly update the app if a previous version is already installed.

**Comment by HODLERTECH** [comment]
Due to profound changes between updates, some of them require uninstalling of the previous version. We inform about this necessity in an email.
