### ISSUE TITLE
Version 0.0.5.5 crashes on startup

### ISSUE THREAD

**Issue by Citiroller** [HODLERTECH/HODLER-Android-App#53]
To update the app I uninstalled the old version and installed the new one.
When the app starts it displays the splash screen and then crashes.
I'm using Android 6.0.1 on a Fairphone 2.
I tried deleting the cache and the app data uninstalled and reinstalled the app and it still crashes when I try to launch the app.

**Comment by DanielMazurFL4RE** [comment]
Is there any message while crashing?

**Comment by Citiroller** [comment]
No, just the standard Android message when an app stops working that "HODLER Core" was closed.

**Comment by DanielMazurFL4RE** [comment]
Is this reproducable on another devices with similar specs?
