### ISSUE TITLE
History view of coins is lacking descriptions

### ISSUE THREAD

**Issue by raven6679** [HODLERTECH/HODLER-Android-App#56]
In history view, there should be descriptive fields. I mean, labels like "my wallet", "received from", "sent to" etc.

**Comment by raven6679** [comment]
![obraz](https://user-images.githubusercontent.com/33216907/42875833-21473216-8a85-11e8-9a0b-7e5fd5d77341.png)

**Comment by HODLERTECH** [comment]
Thank you. It's a good idea, we will add link to the blockexplorer too.
