### ISSUE TITLE
Seed generation heavily loads or suspends the phone

### ISSUE THREAD

**Issue by HODLERTECH** [HODLERTECH/HODLER-Android-App#60]
Surely there is a solution to not go on a compromise with security, maybe there should be a pop up warning?

After pressing "generate a seed", the warning could display the message, "Note, seed generation may take several seconds, it is absolutely necessary for the seed to be generated in an absolutely safe and fully random manner"
The warning could contain options to continue and cancel.

In addition, after such a message it's great how to lower the priority of this process so that the phone does not hang and instead add progress status bar or any progress animation, no one will complain about these voices, instead people will feel satisfied, calm and aware that they have generated safe seed

**Comment by DanielMazurFL4RE** [comment]
Due the TCA Algorithm (Time Cost Algoritm is a mix of Triple-SHA256 and Bob Jenkins), which result is a password for Speck Algoritm, a part where master seed is accessed, may take few seconds on ARM processor to decrypt it.  In this time application should show an indicator or warning that decrypting process is in progress. At this moment it would show at generating seed and adding new coin or token into wallets list. 

My suggestion: 

- Add indicator for TCA Progress,
- Move TCA to another thread to nonblocking main loop (it creates Hung up warning on Android)
- Add warning about time in generation of seed

TCA at alpha stage:
`function TCA(dane: AnsiString): AnsiString;
var
  i: integer;
  s: AnsiString;

begin
  s := dane;

  for i := 0 to TCAIterations do
    s := GetStrHashSHA256
      (GetStrHashSHA256(GetStrHashSHA256(GetStrHashBobJenkins(s))));
  result := s;
end;`
