### ISSUE TITLE
Add .json keystore file for ETH and tokens compatible with MEW

### ISSUE THREAD

**Issue by HODLERTECH** [HODLERTECH/HODLER-Android-App#7]
as backup

**Comment by DanielMazurFL4RE** [comment]
My idea: Share ,json file feature (Android-like share) to quickly send json file, instead of manually coping via SD Card or USB.
What do you think?

**Comment by HODLERTECH** [comment]
ok

**Comment by HODLERTECH** [comment]
duplicate
